name: Automatic Build Updater

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  Updating:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the master branch
        uses: actions/checkout@v1
        with:
          ref: master
      - name: Set git to commit Linux like line endings
        run: git config --global core.autocrlf true
      - name: Install lxml 4.4.1
        run: python3.6 -m pip install -r requirements.txt
      - name: Download and Parse the Windows Builds
        run: python3.6 -m tools
      - name: Commit changed files
        uses: stefanzweifel/git-auto-commit-action@v2.1.0
        with:
          commit_message: Added updated list of Builds for Linux and Windows systems
          branch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
